# Generated by Django 5.2.7 on 2025-11-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
