# Generated by Django 5.2.7 on 2025-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_contact_created_at_contact_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="contact",
            name="lastfirst_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
